$(document).ready(function(){
    $('#menuContainer').load('./html/header.html');
    $('#principalContainer').load('./html/principal.html');
    $('#crearcuentaContainer').load('./html/crear.html');
    $('#inicioContainer').load('./html/inicio.html');
    $('#inicioadminContainer').load('./html/inicioadmin.html');
    $('#footerContainer').load('./html/footer.html');
    $('#userContainer').load('./html/usuario.html');
    $('#menu2Container').load('./html/header2.html');
    $('#navbaradminContainer').load('./html/navbaradmin.html');
    $('#slideradminContainer').load('./html/slider.html');
    $('#footeradminContainer').load('./html/footeradmin.html');
  });